### ISSUE TITLE
[2021.05.13] 프로그래머스 / Level-3 / 순위

### ISSUE THREAD

**Issue by cckn** [Coding-Test-Learning-Class/Coding-Test-Rep#4]
# [순위](https://programmers.co.kr/learn/courses/30/lessons/49191)

![image](https://user-images.githubusercontent.com/19545278/118060728-612e6f00-b3ce-11eb-90ab-827706c5dd74.png)

**Comment by cckn** [comment]
![image](https://user-images.githubusercontent.com/19545278/118073380-ac547c00-b3e6-11eb-8805-efadcec79880.png)

``` js
function solution(n, results) {
  const graph = Array(n + 1)
    .fill(0)
    .map(() => Array(n + 1).fill(Infinity))

  for (let i = 0; i < n; i++) {
    const idx = i + 1
    graph[idx][idx] = 0
  }

  results.forEach(([a, b]) => {
    graph[a][b] = 1
    graph[b][a] = -1
  })

  for (let k = 1; k <= n; k++)
    for (let i = 1; i <= n; i++)
      for (let j = 1; j <= n; j++)
        if (graph[i][k] == 1 && graph[k][j] == 1) {
          graph[i][j] = 1
        } else if (graph[i][k] == -1 && graph[k][j] == -1) {
          graph[i][j] = -1
        }

  const result = graph.filter((row) => {
    return row.every((element, idx) => {
      if (idx === 0) return true
      return element !== Infinity
    })
  }).length
  return result
}

solution(5, [
  [4, 3],
  [4, 2],
  [3, 2],
  [1, 2],
  [2, 5],
]) //?


```

**Comment by kiJu2** [comment]
![image](https://user-images.githubusercontent.com/50073258/118458932-2f066f80-b736-11eb-9661-9994a7704514.png)

```javascript
function solution(n, results) {
  const graph = 
        new Array(n)
        .fill()
        .map(_=> new Array(n).fill(false));
  graph.map((_,idx) => graph[idx][idx]=0);

  results.map(v=>{
    const [win, lose] = [v[0]-1, v[1]-1];
    graph[win][lose] = 1;
    graph[lose][win] = -1;
  })
  
  for(let mid=0; mid<graph.length; mid++){
    for(let a=0; a<graph.length; a++){
      for(let b=0; b<graph.length; b++){
        if(graph[a][mid] === 1&& graph[mid][b] === 1) graph[a][b] =1;
        if(graph[a][mid] === -1&& graph[mid][b] === -1) graph[a][b] =-1;
      }
    }
  }

  return graph.filter(column => !column.includes(false)).length;
}
```

**Comment by kiJu2** [comment]
이 문제를 풀다가 발생한 문제인데요. 혹시 아시는 분 있으신가요?
for문을 통하여 문제를 해결하면 되는데, map을 통해서 for문을 돌리는 것처럼 작성할 때는 런타임 에러가 발생하네요.

```javascript
function solution(n, results) {
  const graph = 
        new Array(n)
        .fill()
        .map(_=> new Array(n).fill(false));
  graph.map((_,idx) => graph[idx][idx]=0);

  results.map(v=>{
    const [win, lose] = [v[0]-1, v[1]-1];
    graph[win][lose] = 1;
    graph[lose][win] = -1;
  })
  
  for(let mid=0; mid<graph.length; mid++){
    for(let a=0; a<graph.length; a++){
      for(let b=0; b<graph.length; b++){
        if(graph[a][mid] === 1&& graph[mid][b] === 1) graph[a][b] =1;
        if(graph[a][mid] === -1&& graph[mid][b] === -1) graph[a][b] =-1;
      }
    }
  }
  // results.map((_,mid)=>{
  //   results.map((_,a)=>{
  //     results.map((_,b)=>{
  //       if(graph[a][mid] === 1 && graph[mid][b] == 1) graph[a][b] = 1;
  //       if(graph[a][mid] === -1 && graph[mid][b] === -1) graph[a][b] = -1;
  //     })
  //   })
  // });

  return graph.filter(column => !column.includes(false)).length;
}
```
같은 로직이며 접근하는 idx 순서는 같습니다.
주석 처리된 부분으로 연쇄 승리를 추적하면 프로그래머스 내에서 런타임 에러 혹은 실패가 뜨는데 혹시 아시는 분 있으신가요?

**Comment by kiJu2** [comment]
> 이 문제를 풀다가 발생한 문제인데요. 혹시 아시는 분 있으신가요?
> for문을 통하여 문제를 해결하면 되는데, map을 통해서 for문을 돌리는 것처럼 작성할 때는 런타임 에러가 발생하네요.
> 
> ```js
> function solution(n, results) {
>   const graph = 
>         new Array(n)
>         .fill()
>         .map(_=> new Array(n).fill(false));
>   graph.map((_,idx) => graph[idx][idx]=0);
> 
>   results.map(v=>{
>     const [win, lose] = [v[0]-1, v[1]-1];
>     graph[win][lose] = 1;
>     graph[lose][win] = -1;
>   })
>   
>   for(let mid=0; mid<graph.length; mid++){
>     for(let a=0; a<graph.length; a++){
>       for(let b=0; b<graph.length; b++){
>         if(graph[a][mid] === 1&& graph[mid][b] === 1) graph[a][b] =1;
>         if(graph[a][mid] === -1&& graph[mid][b] === -1) graph[a][b] =-1;
>       }
>     }
>   }
>   // results.map((_,mid)=>{
>   //   results.map((_,a)=>{
>   //     results.map((_,b)=>{
>   //       if(graph[a][mid] === 1 && graph[mid][b] == 1) graph[a][b] = 1;
>   //       if(graph[a][mid] === -1 && graph[mid][b] === -1) graph[a][b] = -1;
>   //     })
>   //   })
>   // });
> 
>   return graph.filter(column => !column.includes(false)).length;
> }
> ```
> 
> 같은 로직이며 접근하는 idx 순서는 같습니다.
> 주석 처리된 부분으로 연쇄 승리를 추적하면 프로그래머스 내에서 런타임 에러 혹은 실패가 뜨는데 혹시 아시는 분 있으신가요?
